/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartHereRouteImport } from './routes/start-here'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DesignRouteImport } from './routes/design'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareShareTokenRouteImport } from './routes/share.$shareToken'
import { Route as KitKitIdRouteImport } from './routes/kit.$kitId'
import { Route as DesignHistoryRouteImport } from './routes/design.history'
import { Route as DesignHistoryDiffRouteImport } from './routes/design.history.diff'

const StartHereRoute = StartHereRouteImport.update({
  id: '/start-here',
  path: '/start-here',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareTokenRoute = ShareShareTokenRouteImport.update({
  id: '/share/$shareToken',
  path: '/share/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const KitKitIdRoute = KitKitIdRouteImport.update({
  id: '/kit/$kitId',
  path: '/kit/$kitId',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignHistoryRoute = DesignHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DesignRoute,
} as any)
const DesignHistoryDiffRoute = DesignHistoryDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => DesignHistoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRouteWithChildren
  '/library': typeof LibraryRoute
  '/start-here': typeof StartHereRoute
  '/design/history': typeof DesignHistoryRouteWithChildren
  '/kit/$kitId': typeof KitKitIdRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/design/history/diff': typeof DesignHistoryDiffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRouteWithChildren
  '/library': typeof LibraryRoute
  '/start-here': typeof StartHereRoute
  '/design/history': typeof DesignHistoryRouteWithChildren
  '/kit/$kitId': typeof KitKitIdRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/design/history/diff': typeof DesignHistoryDiffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRouteWithChildren
  '/library': typeof LibraryRoute
  '/start-here': typeof StartHereRoute
  '/design/history': typeof DesignHistoryRouteWithChildren
  '/kit/$kitId': typeof KitKitIdRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/design/history/diff': typeof DesignHistoryDiffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/library'
    | '/start-here'
    | '/design/history'
    | '/kit/$kitId'
    | '/share/$shareToken'
    | '/design/history/diff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/library'
    | '/start-here'
    | '/design/history'
    | '/kit/$kitId'
    | '/share/$shareToken'
    | '/design/history/diff'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/library'
    | '/start-here'
    | '/design/history'
    | '/kit/$kitId'
    | '/share/$shareToken'
    | '/design/history/diff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  StartHereRoute: typeof StartHereRoute
  KitKitIdRoute: typeof KitKitIdRoute
  ShareShareTokenRoute: typeof ShareShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start-here': {
      id: '/start-here'
      path: '/start-here'
      fullPath: '/start-here'
      preLoaderRoute: typeof StartHereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareToken': {
      id: '/share/$shareToken'
      path: '/share/$shareToken'
      fullPath: '/share/$shareToken'
      preLoaderRoute: typeof ShareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit/$kitId': {
      id: '/kit/$kitId'
      path: '/kit/$kitId'
      fullPath: '/kit/$kitId'
      preLoaderRoute: typeof KitKitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/history': {
      id: '/design/history'
      path: '/history'
      fullPath: '/design/history'
      preLoaderRoute: typeof DesignHistoryRouteImport
      parentRoute: typeof DesignRoute
    }
    '/design/history/diff': {
      id: '/design/history/diff'
      path: '/diff'
      fullPath: '/design/history/diff'
      preLoaderRoute: typeof DesignHistoryDiffRouteImport
      parentRoute: typeof DesignHistoryRoute
    }
  }
}

interface DesignHistoryRouteChildren {
  DesignHistoryDiffRoute: typeof DesignHistoryDiffRoute
}

const DesignHistoryRouteChildren: DesignHistoryRouteChildren = {
  DesignHistoryDiffRoute: DesignHistoryDiffRoute,
}

const DesignHistoryRouteWithChildren = DesignHistoryRoute._addFileChildren(
  DesignHistoryRouteChildren,
)

interface DesignRouteChildren {
  DesignHistoryRoute: typeof DesignHistoryRouteWithChildren
}

const DesignRouteChildren: DesignRouteChildren = {
  DesignHistoryRoute: DesignHistoryRouteWithChildren,
}

const DesignRouteWithChildren =
  DesignRoute._addFileChildren(DesignRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRouteWithChildren,
  LibraryRoute: LibraryRoute,
  StartHereRoute: StartHereRoute,
  KitKitIdRoute: KitKitIdRoute,
  ShareShareTokenRoute: ShareShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
