/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareShareTokenRouteImport } from './routes/share.$shareToken'
import { Route as AuthenticatedStartHereRouteImport } from './routes/_authenticated/start-here'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedDesignRouteImport } from './routes/_authenticated/design'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedKitKitIdRouteImport } from './routes/_authenticated/kit.$kitId'
import { Route as AuthenticatedDesignHistoryRouteImport } from './routes/_authenticated/design.history'
import { Route as AuthenticatedDesignHistoryDiffRouteImport } from './routes/_authenticated/design.history.diff'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareTokenRoute = ShareShareTokenRouteImport.update({
  id: '/share/$shareToken',
  path: '/share/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStartHereRoute = AuthenticatedStartHereRouteImport.update({
  id: '/start-here',
  path: '/start-here',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignRoute = AuthenticatedDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedKitKitIdRoute = AuthenticatedKitKitIdRouteImport.update({
  id: '/kit/$kitId',
  path: '/kit/$kitId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesignHistoryRoute =
  AuthenticatedDesignHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedDesignRoute,
  } as any)
const AuthenticatedDesignHistoryDiffRoute =
  AuthenticatedDesignHistoryDiffRouteImport.update({
    id: '/diff',
    path: '/diff',
    getParentRoute: () => AuthenticatedDesignHistoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitors': typeof CompetitorsRoute
  '/keywords': typeof KeywordsRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/design': typeof AuthenticatedDesignRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/start-here': typeof AuthenticatedStartHereRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/design/history': typeof AuthenticatedDesignHistoryRouteWithChildren
  '/kit/$kitId': typeof AuthenticatedKitKitIdRoute
  '/design/history/diff': typeof AuthenticatedDesignHistoryDiffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitors': typeof CompetitorsRoute
  '/keywords': typeof KeywordsRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/design': typeof AuthenticatedDesignRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/start-here': typeof AuthenticatedStartHereRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/design/history': typeof AuthenticatedDesignHistoryRouteWithChildren
  '/kit/$kitId': typeof AuthenticatedKitKitIdRoute
  '/design/history/diff': typeof AuthenticatedDesignHistoryDiffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/competitors': typeof CompetitorsRoute
  '/keywords': typeof KeywordsRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/design': typeof AuthenticatedDesignRouteWithChildren
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/start-here': typeof AuthenticatedStartHereRoute
  '/share/$shareToken': typeof ShareShareTokenRoute
  '/_authenticated/design/history': typeof AuthenticatedDesignHistoryRouteWithChildren
  '/_authenticated/kit/$kitId': typeof AuthenticatedKitKitIdRoute
  '/_authenticated/design/history/diff': typeof AuthenticatedDesignHistoryDiffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competitors'
    | '/keywords'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/design'
    | '/library'
    | '/start-here'
    | '/share/$shareToken'
    | '/design/history'
    | '/kit/$kitId'
    | '/design/history/diff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competitors'
    | '/keywords'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/design'
    | '/library'
    | '/start-here'
    | '/share/$shareToken'
    | '/design/history'
    | '/kit/$kitId'
    | '/design/history/diff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/competitors'
    | '/keywords'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/design'
    | '/_authenticated/library'
    | '/_authenticated/start-here'
    | '/share/$shareToken'
    | '/_authenticated/design/history'
    | '/_authenticated/kit/$kitId'
    | '/_authenticated/design/history/diff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CompetitorsRoute: typeof CompetitorsRoute
  KeywordsRoute: typeof KeywordsRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ShareShareTokenRoute: typeof ShareShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareToken': {
      id: '/share/$shareToken'
      path: '/share/$shareToken'
      fullPath: '/share/$shareToken'
      preLoaderRoute: typeof ShareShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/start-here': {
      id: '/_authenticated/start-here'
      path: '/start-here'
      fullPath: '/start-here'
      preLoaderRoute: typeof AuthenticatedStartHereRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design': {
      id: '/_authenticated/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AuthenticatedDesignRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/kit/$kitId': {
      id: '/_authenticated/kit/$kitId'
      path: '/kit/$kitId'
      fullPath: '/kit/$kitId'
      preLoaderRoute: typeof AuthenticatedKitKitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/design/history': {
      id: '/_authenticated/design/history'
      path: '/history'
      fullPath: '/design/history'
      preLoaderRoute: typeof AuthenticatedDesignHistoryRouteImport
      parentRoute: typeof AuthenticatedDesignRoute
    }
    '/_authenticated/design/history/diff': {
      id: '/_authenticated/design/history/diff'
      path: '/diff'
      fullPath: '/design/history/diff'
      preLoaderRoute: typeof AuthenticatedDesignHistoryDiffRouteImport
      parentRoute: typeof AuthenticatedDesignHistoryRoute
    }
  }
}

interface AuthenticatedDesignHistoryRouteChildren {
  AuthenticatedDesignHistoryDiffRoute: typeof AuthenticatedDesignHistoryDiffRoute
}

const AuthenticatedDesignHistoryRouteChildren: AuthenticatedDesignHistoryRouteChildren =
  {
    AuthenticatedDesignHistoryDiffRoute: AuthenticatedDesignHistoryDiffRoute,
  }

const AuthenticatedDesignHistoryRouteWithChildren =
  AuthenticatedDesignHistoryRoute._addFileChildren(
    AuthenticatedDesignHistoryRouteChildren,
  )

interface AuthenticatedDesignRouteChildren {
  AuthenticatedDesignHistoryRoute: typeof AuthenticatedDesignHistoryRouteWithChildren
}

const AuthenticatedDesignRouteChildren: AuthenticatedDesignRouteChildren = {
  AuthenticatedDesignHistoryRoute: AuthenticatedDesignHistoryRouteWithChildren,
}

const AuthenticatedDesignRouteWithChildren =
  AuthenticatedDesignRoute._addFileChildren(AuthenticatedDesignRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDesignRoute: typeof AuthenticatedDesignRouteWithChildren
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedStartHereRoute: typeof AuthenticatedStartHereRoute
  AuthenticatedKitKitIdRoute: typeof AuthenticatedKitKitIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDesignRoute: AuthenticatedDesignRouteWithChildren,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedStartHereRoute: AuthenticatedStartHereRoute,
  AuthenticatedKitKitIdRoute: AuthenticatedKitKitIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CompetitorsRoute: CompetitorsRoute,
  KeywordsRoute: KeywordsRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ShareShareTokenRoute: ShareShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
